DECLARE @VPID AS INT; SELECT @VPID=924
USE PROSPECTPOOL; SET NOCOUNT ON;
PRINT ' =====> SOURCES'
SELECT * FROM SOURCES WHERE PROSPECTID=@VPID
PRINT ' =====> SOURCES HISTORY '
SELECT * FROM SOURCES_HISTORY WHERE PROSPECTID=@VPID
PRINT ' '

PRINT ' =====> RSM'
SELECT PROSPECTID, [M_POSTAL],[M_LNAME],[M_FNAME],[M_CIVICNUM],[M_STREET],[M_SUITENUM], [M_GENERAL], [M_POBOX], [M_RURAL], [M_GD], LNAME, FNAME, NAMEPREFIX         FROM RSMCUSTOMER  WHERE PROSPECTID=@VPID
PRINT ' =====> VISA'
SELECT PROSPECTID, [M_POSTAL],[M_LNAME],[M_FNAME],[M_CIVICNUM],[M_STREET],[M_SUITENUM], [M_GENERAL], [M_POBOX], [M_RURAL], [M_GD], LNAME, FNAME, NAMEPREFIX, DSE_ID FROM VISA         WHERE PROSPECTID=@VPID
PRINT ' =====> APP'
SELECT PROSPECTID, [M_POSTAL],[M_LNAME],[M_FNAME],[M_CIVICNUM],[M_STREET],[M_SUITENUM], [M_GENERAL], [M_POBOX], [M_RURAL], [M_GD], APP_ID, LNAME, FNAME, NAMEPREFIX FROM APPLICATION  WHERE PROSPECTID=@VPID
PRINT ' =====> UC1'
SELECT PROSPECTID, [M_POSTAL],[M_LNAME],[M_FNAME],[M_CIVICNUM],[M_STREET],[M_SUITENUM], [M_GENERAL], [M_POBOX], [M_RURAL], [M_GD], CS_ID, LNAME, FNAME, NAMEPREFIX  FROM INFODIRECT   WHERE PROSPECTID=@VPID
PRINT ' =====> UC2'
SELECT PROSPECTID, [M_POSTAL],[M_LNAME],[M_FNAME],[M_CIVICNUM],[M_STREET],[M_SUITENUM], [M_GENERAL], [M_POBOX], [M_RURAL], [M_GD], CS_ID, LNAME, FNAME, NAMEPREFIX  FROM UCPHASE2     WHERE PROSPECTID=@VPID
PRINT ' =====> UC3'
SELECT PROSPECTID, [M_POSTAL],[M_LNAME],[M_FNAME],[M_CIVICNUM],[M_STREET],[M_SUITENUM], [M_GENERAL], [M_POBOX], [M_RURAL], [M_GD], CS_ID, LNAME, FNAME, NAMEPREFIX  FROM UCPHASE3     WHERE PROSPECTID=@VPID
PRINT ' =====> UC4'
SELECT PROSPECTID, [M_POSTAL],[M_LNAME],[M_FNAME],[M_CIVICNUM],[M_STREET],[M_SUITENUM], [M_GENERAL], [M_POBOX], [M_RURAL], [M_GD],        LNAME, FNAME, NAMEPREFIX  FROM UCPHASE4     WHERE PROSPECTID=@VPID
PRINT ' =====> ES'
SELECT PROSPECTID, [M_POSTAL],[M_LNAME],[M_FNAME],[M_CIVICNUM],[M_STREET],[M_SUITENUM], [M_GENERAL], [M_POBOX], [M_RURAL], [M_GD],        LNAME, FNAME, NAMEPREFIX  FROM EnhancedScan WHERE PROSPECTID=@VPID 
PRINT ' '



PRINT '=====> PROSPECT '
SELECT PROSPECTID, [M_POSTAL],[M_LNAME],[M_FNAME],[M_CIVICNUM],[M_STREET],[M_SUITENUM], [M_GENERAL], [M_POBOX], [M_RURAL], [M_GD], LNAME,FNAME, NAMEPREFIX, Flag_AnalysisOnly, TOPMERGEFILEPRIORITY, LastUpdatedDate, RSM_ID, DSE_ID, APP_ID, CS_ID FROM PROSPECT WHERE PROSPECTID=@VPID
PRINT '=====> PAD '
SELECT *                                                                                                                                                            FROM ProspectAcquisitionDate WHERE PROSPECTID=@VPID

PRINT '=====> FLAGS '
SELECT PROSPECTID, Flag_AnalysisOnly, Flag_NameDeadDeceased	,Flag_NameEstateOf 	,Flag_NameBusiness	,Flag_NameChildChildren 	,Flag_NameReligiousTitle	,Flag_NameAttention	,Flag_NameProfane	,Flag_FNameInitialOnly	,Flag_FNameMissing 	,Flag_LNameMissing             ,Flag_LName1Letter 	,Flag_FNameLonger17 	,Flag_LNameLonger17	,Flag_AddrNameInCareOf	,Flag_CityMissing 	,Flag_CityLonger27 	,Flag_AddrNurRetHome 	,Flag_InvalidPC	,Flag_GovernmentFSA 	,Flag_GovernmentPC	,Flag_AddrFieldsEmpty	,Flag_AddrHotelMotelInn 	,Flag_AddrLargeVolumeR 	,Flag_Nixie	,Flag_InvalidAddr          
FROM PROSPECT WHERE PROSPECTID=@VPID



--SELECT * FROM ProspectAcquisitionDate WHERE PROSPECTID=@VPID
--SELECT PROSPECTID, RSM_ID, DSE_ID, CS_ID, TOPMERGEFILEPRIORITY, LASTUPDATEDDATE, RECENTACQUISITIONDATE FROM PROSPECT WHERE PROSPECTID=@VPID
--SP_WHO2

