PRINT ' =====> PAD'
SELECT PROSPECTID, [M_POSTAL],[M_LNAME],[M_FNAME],[M_CIVICNUM],[M_STREET],[M_SUITENUM], [M_GENERAL], [M_POBOX], [M_RURAL], [M_GD]                                           FROM ProspectAcquisitionDate       WHERE PROSPECTID IN (16566592,13998166,22271312)
PRINT ' =====> PROSPECT'
SELECT PROSPECTID, [M_POSTAL],[M_LNAME],[M_FNAME],[M_CIVICNUM],[M_STREET],[M_SUITENUM], [M_GENERAL], [M_POBOX], [M_RURAL], [M_GD], TopMergeFilePriority, Flag_AnalysisOnly  FROM PROSPECT          WHERE PROSPECTID IN (16566592,13998166,22271312)
PRINT ' =====> RSM_STAGE'
SELECT PROSPECTID, [M_POSTAL],[M_LNAME],[M_FNAME],[M_CIVICNUM],[M_STREET],[M_SUITENUM], [M_GENERAL], [M_POBOX], [M_RURAL], [M_GD], FLAG_PROSPECTMATCH                       FROM STAGEDB.DBO.RSMCUSTOMER_STAGE WHERE PROSPECTID IN (16566592,13998166,22271312) 
PRINT ' '
