USE PROSPECTPOOL
SELECT COUNT(*) AS NO FROM RSMCustomer
SELECT COUNT(*) FROM SOURCES WHERE FILEID=9
SELECT COUNT(*) AS NO FROM APPLICATION
SELECT COUNT(*) FROM SOURCES WHERE FILEID=8
SELECT COUNT(*) AS NO FROM VISA
SELECT COUNT(*) FROM SOURCES WHERE FILEID=7
SELECT COUNT(*) AS NO FROM INFODIRECT
SELECT COUNT(*) FROM SOURCES WHERE FILEID=1
SELECT COUNT(*) AS NO FROM UCPhase2
SELECT COUNT(*) FROM SOURCES WHERE FILEID=2
SELECT COUNT(*) AS NO FROM UCPhase3
SELECT COUNT(*) FROM SOURCES WHERE FILEID=3
SELECT COUNT(*) AS NO FROM UCPhase4
SELECT COUNT(*) FROM SOURCES WHERE FILEID=5
