USE AUDITDB; DECLARE @AUDITNO INT; SELECT @AUDITNO = 1051 --(SELECT MAX(AUDIT_ID) FROM AUDIT_JOB );
SELECT * FROM AUDIT_JOB  WHERE AUDIT_ID=@AUDITNO 
SELECT * FROM AUDIT_TASK WHERE AUDIT_ID=@AUDITNO ORDER BY TASK_START_DT   
SELECT * FROM AUDIT_DATA WHERE AUDIT_ID=@AUDITNO 
--SELECT * FROM PROSPECTPOOL.DBO.ACTIVEFILES
--SELECT * FROM VIEW_AUDIT

--CLEAN UP AUDIT  
--SP_WHO2
--TRUNCATE TABLE AUDIT_TASK; TRUNCATE TABLE AUDIT_DATA; TRUNCATE TABLE AUDIT_DATA_DETAILS; DELETE FROM AUDIT_JOB;

--SELECT Q_CORRECTSTATUS, QNCOA_STATUS, COUNT (*) AS NO FROM STAGEDB.DBO.INFODIRECT_STAGE GROUP BY Q_CORRECTSTATUS, QNCOA_STATUS