--SELECT StageDB.dbo.CreateMatchCodes_BusinessNameIMPN('A')
--SELECT StageDB.dbo.CreateMatchCodes_BusinessNameIMPN('CORP')
--SELECT StageDB.dbo.CreateMatchCodes_BusinessNameIMPN('INC DDD')
--SELECT StageDB.dbo.CreateMatchCodes_BusinessNameIMPN('DDD INC')

SELECT StageDB.dbo.CreateMatchCodes_BusinessNameIMPN('INC CORP  DDDÇDDDDD  BBBBBB   CCCCC')
SELECT StageDB.dbo.CreateMatchCodes_BusinessNameIMPN('DDDDDDDD  BBBBBB  CORP  CCCCC  INC')
SELECT StageDB.dbo.CreateMatchCodes_BusinessNameIMPN('DDDDDDDD  CORP  BBBBBB  INC  CCCCC')
SELECT StageDB.dbo.CreateMatchCodes_BusinessNameIMPN('DDDDDDDD  INC  BBBBBB  CORP  CCCCC')




--SELECT StageDB.dbo.Clean1('INC CORP  DDDDDDDD  BBBBBB   CCCCC XXXXXXXXXX YYYYYYYYYY WWWWWWWWWWWWW')
--SELECT StageDB.dbo.Clean1('DDDDDDDD  BBBBBB  CORP  CCCCC  INC XXXXXXXXXX YYYYYYYYYY WWWWWWWWWWWWW')
--SELECT StageDB.dbo.Clean1('DDDDDDDD  CORP  BBBBBB  INC  CCCCC XXXXXXXXXX YYYYYYYYYY WWWWWWWWWWWWW')
--SELECT StageDB.dbo.Clean1('DDDDDDDD  INC  BBBBBB  CORP  CCCCC XXXXXXXXXX YYYYYYYYYY WWWWWWWWWWWWW')

/*
UPDATE TESTBN SET M_BusName=''
SELECT TOP 100 * FROM TESTBN
SELECT CHARINDEX(' ','123456 890 44465 ',100)
UPDATE TESTBN SET M_BusNameN=StageDB.dbo.CreateMatchCodes_BusinessNameIMPN(BusName) --24 SEC
--UPDATE TESTBN SET M_BusName=StageDB.dbo.CreateMatchCodes_BusinessName(BusName) --26 SEC
*/



SELECT UPPER('î')

