USE AUDITDB; DECLARE @AUDITNO INT; SELECT @AUDITNO =(SELECT MAX(AUDIT_ID) FROM AUDIT_JOB );
SELECT * FROM AUDIT_JOB  WHERE AUDIT_ID=@AUDITNO 
SELECT * FROM AUDIT_TASK WHERE AUDIT_ID=@AUDITNO 
SELECT * FROM AUDIT_DATA WHERE AUDIT_ID=@AUDITNO 
SELECT * FROM ProspectPool.dbo.ActiveFiles
--SELECT * FROM VIEW_AUDIT

--CLEAN UP AUDIT
--TRUNCATE TABLE AUDIT_TASK; TRUNCATE TABLE AUDIT_DATA; TRUNCATE TABLE Audit_Data_Details; DELETE FROM AUDIT_JOB;

