USE PROSPECTPOOL;

TRUNCATE TABLE DedupedProspects;
TRUNCATE TABLE SOURCES;
TRUNCATE TABLE SOURCES_HISTORY;
TRUNCATE TABLE RSMCustomer;
TRUNCATE TABLE VISA;
TRUNCATE TABLE Application;
TRUNCATE TABLE INFODIRECT;
TRUNCATE TABLE UCPhase2;
TRUNCATE TABLE UCPhase3;
TRUNCATE TABLE EnhancedScan;
TRUNCATE TABLE NewProspects;
TRUNCATE TABLE SUPPRESSIONS
DELETE FROM VALIDPHONES
DELETE FROM ProspectAcquisitionDate
DELETE FROM PROSPECT
TRUNCATE TABLE VisaID_InActive_History

USE STOREDB
TRUNCATE TABLE RPT_STATS_QCODE
TRUNCATE TABLE RPT_STATS_QNCOA

