-- Flag duplicates;
;WITH Dups AS (SELECT Address, COUNT(*) as qty FROM StageDB.[dbo].[Dealers] WHERE LEN(Address)>0 GROUP BY Address HAVING COUNT(*)>1)
UPDATE StageDB.[dbo].[Dealers] SET [Flag_Dup_Address]='Y' WHERE Address IN (SELECT DISTINCT Address FROM Dups); 



UPDATE INFODIRECT_STAGE SET Flag_IntraFileDedup=1 WHERE ROWID NOT IN
(SELECT MIN(ROWID) FROM INFODIRECT_STAGE A WHERE A.FLAG_IntraFileDedupPriority IN 
(SELECT MIN(FLAG_IntraFileDedupPriority) FROM INFODIRECT_STAGE
GROUP BY M_POSTAL, M_LNAME, M_FNAME, M_CIVICNUM, M_STREET, M_SUITENUM, M_GENERAL, M_POBOX,M_RURAL, M_GD )
GROUP BY M_POSTAL, M_LNAME, M_FNAME, M_CIVICNUM, M_STREET, M_SUITENUM, M_GENERAL, M_POBOX,M_RURAL, M_GD )






--SAU

--protariu / 20060315

ALTER  PROC  dbo.usp_STDIntraFileDedup (@vTable varchar(100))

AS


DECLARE @VCMD VARCHAR(8000); SET @VCMD =SPACE(1);

SET @VCMD = @VCMD + 'UPDATE ' + @VTABLE + ' SET Flag_IntraFileDedup=1 WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM '+ @VTABLE + ' 
GROUP BY  M_POSTAL, M_LNAME, M_FNAME, M_CIVICNUM, M_STREET, M_SUITENUM, M_GENERAL, M_POBOX,M_RURAL, M_GD ) ;  '

SET @VCMD = @VCMD + 'UPDATE ' + @VTABLE + ' SET Flag_IntraFileDedup=1 WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM '+ @VTABLE + ' 
GROUP BY  M_POSTAL, M_LNAME, M_FNAME, M_CIVICNUM, M_STREET, M_SUITENUM)
AND LEN(M_CIVICNUM)>0  AND LEN(M_SUITENUM) >0  AND LEN(M_STREET)>0  ; '

SET @VCMD = @VCMD + 'UPDATE ' + @VTABLE + ' SET Flag_IntraFileDedup=1 WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM '+ @VTABLE + ' 
GROUP BY  M_POSTAL, M_LNAME, M_FNAME, M_STREET, M_SUITENUM)
AND LEN(M_STREET)>0  AND LEN(M_SUITENUM)>0  ; '

SET @VCMD = @VCMD + 'UPDATE ' + @VTABLE + ' SET Flag_IntraFileDedup=1 WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM '+ @VTABLE + ' 
GROUP BY  M_POSTAL, M_LNAME, M_FNAME, M_CIVICNUM, M_SUITENUM)
AND LEN(M_CIVICNUM)>0  AND LEN(M_SUITENUM)>0  ; '

SET @VCMD = @VCMD + 'UPDATE ' + @VTABLE + ' SET Flag_IntraFileDedup=1 WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM '+ @VTABLE + ' 
GROUP BY  M_POSTAL, M_LNAME, M_FNAME, M_CIVICNUM, M_STREET)
AND LEN(M_CIVICNUM)>0  AND LEN(M_STREET) >0  ; '

SET @VCMD = @VCMD + 'UPDATE ' + @VTABLE + ' SET Flag_IntraFileDedup=1 WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM '+ @VTABLE + ' 
GROUP BY  M_POSTAL, M_LNAME, M_FNAME, M_GENERAL)
AND LEN(M_GENERAL)>0  ; '

SET @VCMD = @VCMD + 'UPDATE ' + @VTABLE + ' SET Flag_IntraFileDedup=1 WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM '+ @VTABLE + ' 
GROUP BY  M_POSTAL, M_LNAME, M_FNAME, M_POBOX)
AND LEN(M_POBOX)>0   ; '

SET @VCMD = @VCMD + 'UPDATE ' + @VTABLE + ' SET Flag_IntraFileDedup=1 WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM '+ @VTABLE + ' 
GROUP BY  M_POSTAL, M_LNAME, M_FNAME, M_RURAL)
AND LEN(M_RURAL)>0  ;  '

SET @VCMD = @VCMD + 'UPDATE ' + @VTABLE + ' SET Flag_IntraFileDedup=1 WHERE ROWID NOT IN 
(SELECT MIN(ROWID) FROM '+ @VTABLE + ' 
GROUP BY  M_POSTAL, M_LNAME, M_FNAME, M_GD)
AND LEN(M_GD)>0  ;  '


EXEC (@VCMD)





