-- THIS IS SQL2000

REM DTSRUN /SWS443 /E  /NLM_Loading_Manager 
DTSRUN /SWS443 /E  /NZTEST

REM DTSRUN /SWS443 /USA /Ptoronto1  /NLM_Loading_Manager /!Y
REM NU AI FOST IN STARE SA PORNESTI ASTA PUNEL SUB LCADMIN

