-- LastUpdate 20060316
--SELECT * INTO DispositionCodes FROM [DISPOSITIONCODES.20060316]
--SELECT * FROM DispositionCodes ORDER BY PROGID
--SELECT MAX(DISPCODE) FROM DispositionCodes WHERE PROGID=2

SELECT A.PROGID, A.DESCRIPTION, B.DESCRIPTION, A.RESPONSECODE, B.RESPONSECODE FROM DispositionCodes A, TMPEOC B WHERE A.PROGID=B.PROGID AND A.DESCRIPTION=B.DESCRIPTION

--UPDATE EXISTENT
--UPDATE T1 SET T1.RESPONSECODE=T2.RESPONSECODE FROM DispositionCodes T1, TMPEOC T2
--WHERE T1.PROGID=T2.PROGID AND T1.DESCRIPTION=T2.DESCRIPTION

--INSERT NEW
--INSERT INTO DispositionCodes
--   SELECT PROGID, DISPCODE, DESCRIPTION, RESPONSECODE
--   FROM TMPEOC
--   WHERE DISPCODE>0
