CREATE TABLE #T
(
Team varchar (20), Member varchar (20)
)
 
INSERT INTO #T VALUES ('ERP','Jack')
INSERT INTO #T VALUES ('ERP','John')
INSERT INTO #T VALUES ('ERP','Mary')
INSERT INTO #T VALUES ('ERP','Robert')
INSERT INTO #T VALUES ('ERP','Diana')
INSERT INTO #T VALUES ('MHR','Pyt')
INSERT INTO #T VALUES ('MHR','George')
INSERT INTO #T VALUES ('MHR','Anna')
 
SELECT * FROM #T;

SELECT TEAM, 
[1] AS TEAMMEMBER1,
[2] AS TEAMMEMBER2,
[3] AS TEAMMEMBER3
FROM (SELECT TEAM, MEMBER, ROW_NUMBER() OVER (PARTITION BY TEAM ORDER BY MEMBER) AS ROWNUM FROM #T) A
PIVOT (MAX(MEMBER) FOR ROWNUM IN ([1],[2],[3])) AS PVT
