
DELETE FROM PROSPECT WHERE PROSPECTID IN

(

SELECT TOP 100
PROSPECTID FROM PROSPECT 
WHERE 
FLAG_ANALYSISONLY=1 AND 
PROSPECTID NOT IN (SELECT PROSPECTID FROM SOURCES) AND
PROSPECTID NOT IN (SELECT PROSPECTID FROM ValidPhones) AND
LEN(M_POSTAL)=0 AND 
LASTUPDATEDDATE IN ('2007-04-28','2007-04-29')

)
