--UPDATE INFODIRECT_1K SET Q_PARSEDADDRESS=''
SELECT TOP 100 * FROM INFODIRECT_1K
--WHERE QNCOA_MOVEDATE IS NOT NULL
SELECT TOP 100 * FROM INFODIRECT_STAGE
--WHERE QNCOA_MOVEDATE IS NOT NULL
SELECT TOP 100000 * INTO INFODIRECT_STAGE_QCODE FROM INFODIRECT_STAGE

SELECT TOP 3 WORKINGFIELD, ORIG_ADDRESS, ORIG_CITY, ORIG_POSTALCODE, ORIG_PROVINCE,Q_PARSEDADDRESS FROM INFODIRECT_1K WHERE ORIG_LNAME IN ('RYGG','SIMPSON')
SELECT TOP 3 WORKINGFIELD, ORIG_ADDRESS, ORIG_CITY, ORIG_POSTALCODE, ORIG_PROVINCE,Q_PARSEDADDRESS FROM INFODIRECT_STAGE WHERE ORIG_LNAME IN ('RYGG','SIMPSON')

SELECT Q_PARSEDADDRESS FROM INFODIRECT_1K
SELECT Q_PARSEDADDRESS, REPLACE(Q_PARSEDADDRESS,SPACE(3),SPACE(1)) FROM INFODIRECT_1K;
UPDATE INFODIRECT_1K SET Q_PARSEDADDRESS = REPLACE(Q_PARSEDADDRESS,SPACE(3),SPACE(1))
UPDATE INFODIRECT_1K SET Q_PARSEDADDRESS = REPLACE(Q_PARSEDADDRESS,SPACE(2),SPACE(1))
SELECT Q_PARSEDADDRESS FROM INFODIRECT_1K


--EXEC StageDB.dbo.usp_STDQCodeFullApp 'INFODIRECT_1K'
--EXEC StageDB.dbo.usp_STDQNCOAFullApp 'INFODIRECT_1K',1

SELECT STAGEDB.DBO.CreateMatchCodeSTD_MGeneral('218       20 MIDPARK                       CR','')
SELECT STAGEDB.DBO.CreateMatchCodeSTD_MGeneral('218-20 MIDPARK CR  ','')

                   
EXEC STAGEDB.DBO.usp_STDMatchCodesGen 'INFODIRECT_1K'