USE STAGEDB;

UPDATE Template_Stage SET
WorkingField= MASTER.dbo.QCode_GetAddressInfo(Orig_ADDRESS,Orig_CITY,Orig_PROVINCE,Orig_PostalCode)


EXEC usp_QCPopulateQFields 'Template_Stage'

SELECT Q_STREETNumber FROM VIEW_QCODE_C
--SELECT Q_STREETNumber, PATINDEX('% %', Q_STREETNumber) FROM VIEW_QCODE_C
SELECT SUBSTRING(Q_STREETNumber,PATINDEX('% %',Q_STREETNumber)+1,6) FROM VIEW_QCODE_C WHERE PATINDEX('% %',Q_STREETNumber)>1 AND PATINDEX('% %',Q_STREETNumber)<LEN(Q_STREETNumber)

UPDATE TEMPLATE_STAGE SET Q_STREETNumber=SUBSTRING(Q_STREETNumber,PATINDEX('% %',Q_STREETNumber)+1,6) FROM TEMPLATE_STAGE WHERE PATINDEX('% %',Q_STREETNumber)>1 AND PATINDEX('% %',Q_STREETNumber)<LEN(Q_STREETNumber)