--EXEC usp_STDUploadCleansing 'INFODIRECT_STAGE'
--EXEC StageDB.dbo.usp_STDFullApp 'InfoDirect_Stage','N'


DECLARE @VTABLE CHAR(50); SELECT @VTABLE='INFODIRECT_STAGE'
DECLARE @VCMD CHAR(1000); SELECT @VCMD=' '

SELECT @VCMD='SELECT Q_CORRECTSTATUS, COUNT(*) AS NO FROM '+@VTABLE+'  GROUP BY Q_CORRECTSTATUS '
EXEC (@VCMD);
SELECT @VCMD='SELECT QNCOA_STATUS, COUNT(*) AS MOVERS FROM '+@VTABLE+' GROUP BY QNCOA_STATUS '
EXEC (@VCMD);