DECLARE @VARC VARCHAR(40)
SELECT @VARC='ELENA O'+CHAR(39)+'CONOR'
SELECT @VARC
SELECT STAGEDB.DBO.udf_STD_NameCleansing(@VARC)

--SELECT STAGEDB.DBO.udf_STD_AddrCleansing('109-1505 WILSON AVE, TORONTO, ONTARIO, CANADA')
--SELECT STAGEDB.DBO.udf_STD_PhoneCleansing('(416)751-9303')
--SELECT STAGEDB.DBO.udf_STD_CityCleansing('1TOROnto. EAST')
--SELECT STAGEDB.DBO.udf_STD_ProvCleansing('A2')
--SELECT STAGEDB.DBO.udf_STD_PCCleansing('M1A 2L2')


