SELECT  TOP 20   CUST_NB, PROSPECTID, ORIG_FNAME, ORIG_LNAME, ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, Q_PARSEDADDRESS, Q_CORRECTSTATUS
FROM         dbo.AEROPLAN_STAGE
WHERE     (PROSPECTID IN
                          (SELECT     PIDN
                            FROM          PROSPECTPOOL.DBO.TMP_APC_PIDN))