USE PROSPECTPOOL

/*
DELETE FROM PROSPECTPOOL.DBO.Suppressions
DELETE FROM PROSPECTPOOL.DBO.ACTIVEFILES
DELETE FROM PROSPECTPOOL.DBO.FILETYPE
DELETE FROM PROSPECTPOOL.DBO.DunAndBradstreet
DELETE FROM PROSPECTPOOL.DBO.INFODIRECT
DELETE FROM PROSPECTPOOL.DBO.VALIDPHONES
DELETE FROM PROSPECTPOOL.DBO.SOURCES
DELETE FROM PROSPECTPOOL.DBO.ProspectAcquisitionDate
DELETE FROM PROSPECTPOOL.DBO.PROSPECT 
*/

/*
SELECT * INTO PROSPECT_QC FROM PROSPECTPOOL.DBO.PROSPECT
SELECT * INTO INFODIRECT_QC FROM PROSPECTPOOL.DBO.INFODIRECT
SELECT * INTO STAGEDB.DBO.INFODIRECT_STAGE_QC FROM STAGEDB.DBO.INFODIRECT_STAGE
*/

/*
SELECT * INTO PROSPECT_SS FROM PROSPECTPOOL.DBO.PROSPECT
SELECT * INTO INFODIRECT_SS FROM PROSPECTPOOL.DBO.INFODIRECT
SELECT * INTO STAGEDB.DBO.INFODIRECT_STAGE_SS FROM STAGEDB.DBO.INFODIRECT_STAGE
*/

SELECT * FROM PROSPECTPOOL.DBO.PROSPECT WHERE LNAME='PETRU'

SELECT COUNT(*) AS NO FROM STAGEDB.DBO.INFODIRECT_STAGE_QC WHERE INVALIDADDRFLAG='1' 
SELECT COUNT(*) AS NO FROM STAGEDB.DBO.INFODIRECT_STAGE_SS WHERE INVALIDADDRFLAG='1' 


SELECT M_CIVICNUM FROM STAGEDB.DBO.INFODIRECT_STAGE WHERE ROWID=43